[Scia Reto](https://sciareto.org) mind map
> __version__=`1.1`,showJumps=`true`
---

# ドメインの洗い出し

## プレイヤー:誰か

### 登録する

## プレイヤー:ユーザー

### ログインする

### プロフィールを登録する

### プロフィールを編集する

### プロフィールを削除する

### ログアウトする

### 退会する

### グループを作成する
